name: Python app
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        #python-version: ["3.10", "3.11"]
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Run everything
        run: |
          make all
    
      - name: Build the Docker image
        run: docker build --file Dockerfile -t titanic-app .

      - name: Push the Image
        run: docker run -d -p 80:8001 titanic-app
